services:
  # database
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql-my_sulu_project
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      # MYSQL_USER: root
    ports:
      - "3318:3306"
    volumes:
      - mysql-data-sulu_project:/var/lib/mysql

  # php
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-my_sulu_project
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/
      PHP_MEMORY_LIMIT: 1024M
    volumes:
      - ./:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql

  # nginx
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-my_sulu_project
    ports:
      - "8090:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mysql-data-sulu_project: